@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgxOTM1NzB9.LfYcES9ZdgJAXVK09sN1IN2qSlWXxLuh5yQiLQudn3A

### USER CREATE
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Greg",
  "email": "greg@test.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "https://static.vecteezy.com/system/resources/previews/002/318/271/original/user-profile-icon-free-vector.jpg"
}

### USER SHOW
GET http://localhost:3000/users/1.json

### USER UPDATE
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{
  "name": "Gregory",
  "email": "gregory@test.com"
}

### USER DESTROY
DELETE http://localhost:3000/users/4


### EXERCISE INDEX
GET http://localhost:3000/exercises.json

### EXERCISES SHOW
GET http://localhost:3000/exercises/2.json

### ROUTINES CREATE
POST http://localhost:3000/routines.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "exercise_id": 3,
  "reps": 25
}

### ROUTINES UPDATE
PATCH http://localhost:3000/routines/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "reps": "4"
}

### ROUTINES DESTROY
DELETE http://localhost:3000/routines/1
Authorization: Bearer {{jwt}}

### ROUTINES SHOW
GET http://localhost:3000/routines/2.json

### ROUTINES INDEX
GET http://localhost:3000/routines.json
Authorization: Bearer {{jwt}}

### SESSIONS CREATE (LOGIN)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "robbie@test.com",
  "password": "password"
}