### USER CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Greg",
  "email": "greg@test.com",
  "password_digest": "password",
  "image_url": "https://static.vecteezy.com/system/resources/previews/002/318/271/original/user-profile-icon-free-vector.jpg"
}

### USER UPDATE
PATCH http://localhost:3000/users/4
Content-Type: application/json

{
  "name": "Gregory",
  "email": "gregory@test.com"
}

### USER DESTROY
DELETE http://localhost:3000/users/4

